apiVersion: v1
kind: Pod
metadata:
  name: prometheus-pod
  namespace: calico-monitoring
  labels:
    app: prometheus-pod
    role: monitoring
spec:
  serviceAccountName: calico-prometheus-user
  containers:
    - name: prometheus-pod
      image: prom/prometheus
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      ports:
        - containerPort: 9090
  template:
    metadata:
      labels:
        app: prometheus-pod
      annotations:
        ad.datadoghq.com/prometheus-pod.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/prometheus-pod.init_configs: |
          [{}]
        ad.datadoghq.com/prometheus-pod.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:%%port%%/metrics",
              "namespace": "LMQR",
              "metrics": ["felix_active_local_endpoints"]
            }
          ]
  volumes:
    - name: config-volume
      configMap:
        name: prometheus-config
